### ISSUE TITLE
 Cannot find module 'moment-timezone'

### ISSUE THREAD

**Issue by e-zambrano** [felixrieseberg/Ghost-Updater-Azure#11]
Hey,

After trying to update to 0.9.0 I got a 500 error. I am looking at /LogFiles/Application/logging-errors.txt and this is what I got:

> Sun Jul 31 2016 18:24:06 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
> Error: Cannot find module 'moment-timezone'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:289:25)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at Object.<anonymous> (D:\home\site\wwwroot\core\server\overrides.js:1:76)
>     at Module._compile (module.js:435:26)
>     at Object.Module._extensions..js (module.js:442:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:313:12)
>     at Module.require (module.js:366:17)

**Comment by jakarjakar** [comment]
The same error on Ubuntu 14.04

$ sudo npm install --production
$ npm start
> ghost@0.11.4 start /usr/local/bin/ghost
> node index

module.js:471
    throw err;
    ^

Error: Cannot find module 'moment-timezone'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/bin/ghost/core/server/overrides.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by adorabilis** [comment]
@jakarjakar If you're installing Ghost on a VPS with limited ram, make sure swapfile is enabled, then try again. See https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by dsottimano** [comment]
@martianbaby isn't that just an error saying the moment-timezone module isn't installed? I'd be surprised if npm install moment-timezone didn't resolve this issue.
